#==========================
#application configurations
#==========================
spring:
  config:
    activate:
      on-profile: docker
    import: "optional:configserver:http://config-service:8888"

---
spring:
  application:
    name: notification-service
  config:
    import: "optional:configserver:http://localhost:8888"


