#server-configurations
spring:
  application:
    name: service-registry
  zipkin:
    base-url: http://localhost:9411
  cloud:
    compatibility-verifier:
      enabled: false

server:
  port: 8761

#eureka server configuration
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

