#Service configuration
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: bed-service
          uri: lb://BED-SERVICE
          predicates:
            - Path=/api/v1/beds/**
    discovery:
      enabled: true

#eureka server
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 9191
