#Server and datasource configuration
spring:
  application:
    name: bed-service
  datasource:
    url: jdbc:mysql://localhost:3306/bed_db
    username: Chilufya
    password: Kenzie@2023

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  cloud:
    discovery:
      enabled: true

server:
  port: 8080

#eureka client configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    enabled: true
  instance:
    hostname: localhost
    prefer-ip-address: true
