#==========================
#application configurations
#==========================
server:
  port: 8888
spring:
  profiles:
    active: native
  application:
    name: config-server

#===============================
#eureka server configuration
#===============================
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    enabled: true

