#==========================
#application configurations
#==========================
server:
  port: 9292

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/notification_db
    username: Chilufya
    password: Kenzie@2023

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

  cloud:
    discovery:
      enabled: true
  output:
    ansi:
      enabled: always

management:
  endpoints:
    web:
      exposure:
        include: health
  tracing:
    sampling:
      probability: 1.0

---
#====================
#Kafka configurations
#====================
spring:
  kafka:
    bootstrap-servers: "localhost:9092"
    consumer:
      auto-offset-reset: earliest
      group-id: "healthcare-notification"

#===========================
#eureka client configuration
#===========================
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    enabled: true

  instance:
    hostname: localhost
    prefer-ip-address: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %m%n"
---
#====================
#email configurations
#====================
spring:
  mail:
    host: "smtp.gmail.com"
    port: 587
    username: "ksidevsofts@gmail.com"
    password: "AuhYcWwRHwy2xQY"