#==========================
#application configurations
#==========================
server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/patient_registration_db
    username: Chilufya
    password: Kenzie@2023

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

  cloud:
    discovery:
      enabled: true
  output:
    ansi:
      enabled: always

management:
  endpoints:
    web:
      exposure:
        include: health
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %m%n"
---
#====================
#Kafka configurations
#====================
spring:
  kafka:
    bootstrap-servers: "localhost:9092"
    consumer:
      auto-offset-reset: earliest
      group-id: "healthcare-notification"
---
spring:
  kafka:
    template:
      default-topic: "notification"

#=====================
#eureka configurations
#=====================
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost

  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true


