
server:
  port: 8082
---
#========================
#Datasource configuration
#========================
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wards_db
    username: Chilufya
    password: Kenzie@2023

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
---
#===================
#Cloud configuration
#===================
spring:
  cloud:
    discovery:
      enabled: true
  output:
    ansi:
      enabled: always
management:
  endpoints:
    web:
      exposure:
        include: health
  tracing:
    sampling:
      probability: 1.0
---
#=====================
#eureka configurations
#=====================
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost

  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true